name: e_coupon
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ecoupon_lib:
    git:
      url: https://github.com/dudagroup/ecoupon-library.git
      ref: 2b69cc2c5e34a837b712f4a2b62a76f6b4d0aa7b

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  state_notifier: ^0.5.0
  localstorage: ^3.0.2+5
  http: ^0.12.2

  gradient_app_bar: ^0.1.3
  # not needed?
  barcode_scan: any
  # qr generation
  qr_flutter: ^3.1.0
  path_provider: ^1.6.11
  flushbar: ^1.10.4
  provider: ^4.1.3
  device_info: ^0.4.2+4
  url_launcher: ^5.5.0
  rxdart: ^0.24.1
  flutter_typeahead: ^1.8.8
  keyboard_visibility: "0.5.6"
  # multi lang country picker for verification form heimatsort
  country_code_picker: ^1.4.0

  # injection provider arount get it
  injectable: ^1.0.0
  # suggestions from reso coder clean architecture & ttd tutorials
  # Service locator
  get_it: ^4.0.2
  # Value equality
  equatable: ^1.2.2
  # Functional programming thingies
  dartz: ^0.9.1
  # Remote API
  # connectivity: ^0.4.9
  # Local cache
  shared_preferences: ^0.5.8
  # Dart Linting Rules
  pedantic: ^1.9.0
  # SVG
  flutter_svg: ^0.18.0
  # Package Info
  package_info: ^0.4.1
  # qr scan
  qr_code_scanner: ^0.0.13

  # Push Notifications
  firebase_messaging: ^6.0.16

  # Sign-In Third Party Plugins
  flutter_secure_storage: ^3.3.3
  sign_in_with_apple: ^2.5.2
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.4
  build_runner:
  injectable_generator: ^1.0.0
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NewPanam
      fonts:
        # - asset: assets/NewPanamSkyline-Black.ttf
        #   weight: 700
        # - asset: assets/NewPanamSkyline-BlackItalic.ttf
        #   weight: 700
        #   style: italic
        - asset: assets/NewPanamSkyline-Bold.ttf
          weight: 800
        # - asset: assets/NewPanamSkyline-BoldItalic.ttf
        #   weight: 600
        #   style: italic
        - asset: assets/NewPanamSkyline-Medium.ttf
          weight: 500
        # - asset: assets/NewPanamSkyline-MediumItalic.ttf
        #   weight: 500
        #   style: italic
        - asset: assets/NewPanamSkyline-Regular.ttf
          weight: 400
        # - asset: assets/NewPanamSkyline-Italic.ttf
        #   weight: 400
        #   style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
