import 'package:e_coupon/generated/i18n.dart';
import 'package:e_coupon/ui/core/router/router.dart';
import 'package:e_coupon/ui/core/style/theme.dart';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:injectable/injectable.dart';

@injectable
class ECouponApp extends StatelessWidget {
  final Locale _locale = Locale('de', 'CH');

  final IRouter router;

  ECouponApp(this.router);

  @override
  Widget build(BuildContext context) {
    // autogenerated i18n delegate from vscode extension https://github.com/esskar/vscode-flutter-i18n-json
    final i18n = I18n.delegate;

    return MaterialApp(
      localizationsDelegates: [
        i18n,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      locale: _locale,
      supportedLocales: i18n.supportedLocales,
      localeResolutionCallback: i18n.resolution(fallback: Locale("de", "CH")),
      theme: generalTheme,
      title: "ecoo",
      onGenerateRoute: Router.onGenerateRoute,
      navigatorKey: router.navigatorKey,
      initialRoute: SplashRoute,
    );
  }
}
