# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and Sign iOS App and Upload to TestFlight"
  lane :deploy do

    get_provisioning_profile

    build_app(workspace: "Runner.xcworkspace", 
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "ch.ecoupon.mobile" => "eCoupon-AppStore"
        }
      },
      output_name: "Runner-iOS.ipa")
  
    upload_to_testflight

    deliver(
      force: true,
      build_number: ENV['env.VersionMajorMinorPatchBuild'],
      app_version: ENV['env.VersionMajorMinorPatch'],
      skip_binary_upload: true,
      submit_for_review: false,
      automatic_release: false,
    )
  end

end
