# This is a basic workflow to help you get started with Actions

name: CI

# only Branches except 'master'
on:
  push:
    branches:
      - "**"
      - "!releases/**"
    tags-ignore:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.3"
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Lint
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.3"
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Tests
        run: flutter test

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.3"
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Build Android
        run: |
          echo "$KEYSTORE" | base64 --decode > ./android/assets/ecoupon.keystore.jks
          dart tool/generate_config.dart
          flutter build appbundle -t ./lib/main_dev.dart
        env:
          KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_PLAY_API_SA: ${{ secrets.ANDROID_PLAY_API_SA }}
          APP_PAPERWALLET_DECRYPTION_KEY: ${{ secrets.APP_PAPERWALLET_DECRYPTION_KEY }}

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.20.3"
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Build iOS
        run: |
          dart tool/generate_config.dart
          flutter build ios -t ./lib/main_dev.dart --release --no-codesign
        env:
          APP_PAPERWALLET_DECRYPTION_KEY: ${{ secrets.APP_PAPERWALLET_DECRYPTION_KEY }}
