# This is a basic workflow to help you get started with Actions

name: QA

on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Lint
        run: flutter analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.ECOUPON_LIB_GIT_ACCESS_TOKEN}}
      - name: Setup
        run: |
          flutter --version
          flutter pub get
          make generate_code

      - name: Tests
        run: flutter test
